name: luna25_pl_dl_pipeline_template_venv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip
  - python=3.11.11
  - pip:
      - albumentations==2.0.5
      - hydra-core==1.3.2
      - numpy==1.26.0
      - omegaconf==2.3.0
      - pandas==2.2.3
      - plotly==6.0.1
      - pytorch-lightning==2.0.9
      - scikit-learn==1.6.1
      - torch==2.0.1
      - torchvision==0.15.2