data:
  dataset_name: LIDC-IDRI
  data_preprocessing_protocol_number: 1
  dataloader:
    dataset_name: LIDC-IDRI
    data_preprocessing_protocol_number: 1
    data_augmentation:
      apply: false
      augmented_to_original_data_ratio: 2
      parameters:
        number_of_augmentations: 3
        random_rotation_degrees: 10
        random_translation_fraction: 0.1
        random_brightness_intensity_factor: 0.3
        random_contrast_intensity_factor: 0.3
        random_gaussian_blur:
          kernel_size:
          - 3
          - 3
          sigma:
          - 0.1
          - 1.0
        random_gaussian_noise_variance: 0.001
        random_elastic_alpha: 10.0
        random_elastic_sigma: 5.0
    image_numpy_arrays_dir_path: /nas-ctm01/datasets/private/LUCAS/LIDC_IDRI/preprocessed_data/protocol_1/image_numpy_arrays
    input_data_size:
    - 1
    - 32
    - 32
    include_labels:
      lnva:
        mean: false
        std: false
      lnm:
        mean: true
        std: false
    lnva_names:
    - subtlety
    - internal_structure
    - calcification
    - sphericity
    - margin
    - lobulation
    - spiculation
    - texture
    mask_numpy_arrays_dir_path: /nas-ctm01/datasets/private/LUCAS/LIDC_IDRI/preprocessed_data/protocol_1/mask_numpy_arrays
    number_of_lnm_scores: 5
    number_of_k_folds: 5
    seed_value: 1
    score_counts:
      subtlety: 5
      internal_structure: 4
      calcification: 6
      sphericity: 5
      margin: 5
      lobulation: 5
      spiculation: 5
      texture: 5
    test_fraction_of_entire_dataset: 0.2
    torch_dataloader_kwargs:
      batch_size: 32
      num_workers: 4
    use_mode_for_internal_structure_and_calcification: false
    validation_fraction_of_train_set: 0.1
  metadataframe:
    dataset_name: LIDC-IDRI
    data_preprocessing_protocol_number: 1
    lnva:
      names:
      - subtlety
      - internal_structure
      - calcification
      - sphericity
      - margin
      - lobulation
      - spiculation
      - texture
      score_counts:
        subtlety: 5
        internal_structure: 4
        calcification: 6
        sphericity: 5
        margin: 5
        lobulation: 5
        spiculation: 5
        texture: 5
      quantity: 8
    use_mode_for_internal_structure_and_calcification: false
experiment_execution:
  ids:
    experiment_id: 2
    experiment_version_id: 1
  info:
    who: Eduardo de Matos Rodrigues
    what: Hyperparameter optimization
  paths:
    experiment_dir_path: /nas-ctm01/homes/emrodrigues/python_projects/pytorch_lightning_dl_pipeline_template/experiment_results/experiment_2
    experiment_version_dir_path: /nas-ctm01/homes/emrodrigues/python_projects/pytorch_lightning_dl_pipeline_template/experiment_results/experiment_2/version_1
    preprocessed_data_dir_path: /nas-ctm01/datasets/private/LUCAS/LIDC_IDRI/preprocessed_data
    python_project_dir_path: /nas-ctm01/homes/emrodrigues/python_projects/pytorch_lightning_dl_pipeline_template
hyperparameter_grid_based_execution:
  apply: true
  hyperparameter_combination:
    index: 1
    used:
      model.pytorch_lightning_model.hyperparameters.optimiser.kwargs.lr: 1.0e-05
      data.dataloader.torch_dataloader_kwargs.batch_size: 32
      seed_value: 1
  hyperparameter_grid:
    model.pytorch_lightning_model.hyperparameters.optimiser.kwargs.lr:
    - 1.0e-05
    data.dataloader.torch_dataloader_kwargs.batch_size:
    - 32
    seed_value:
    - 1
model:
  model_id: EfNet
  model_name: EfficientNet
  model_pipeline:
    model_id: EfNet
    model_name: EfficientNet
    callbacks:
      model_checkpoints:
      - monitor: val_auroc
        filename: mod=EfNet-exp=X-ver=Y-dtf=Z-{epoch}-var={val_auroc:.3f}
        mode: max
        save_top_k: 1
      - monitor: val_loss
        filename: mod=EfNet-exp=X-ver=Y-dtf=Z-{epoch}-var={val_loss:.3f}
        mode: min
        save_top_k: 1
      - filename: mod=EfNet-exp=X-ver=Y-dtf=Z-{epoch}-var=last_epoch
      model_early_stoppings:
      - monitor: val_auroc
        patience: 5
        mode: max
        verbose: false
    enable_logging: true
    enable_model_early_stopping: false
    finalization:
      delete_model_checkpoints: true
      save_used_data_file_names: true
    pytorch_lightning_model:
      model_id: EfNet
      model_name: EfficientNet
      hyperparameters:
        device: cuda
        number_of_classes: 2
        optimiser:
          type: Adam
          kwargs:
            lr: 1.0e-05
        criterion:
          apply_weights: true
          device: cuda
          metadataframe:
            dataset_name: LIDC-IDRI
            data_preprocessing_protocol_number: 1
            lnva:
              names:
              - subtlety
              - internal_structure
              - calcification
              - sphericity
              - margin
              - lobulation
              - spiculation
              - texture
              score_counts:
                subtlety: 5
                internal_structure: 4
                calcification: 6
                sphericity: 5
                margin: 5
                lobulation: 5
                spiculation: 5
                texture: 5
              quantity: 8
            use_mode_for_internal_structure_and_calcification: false
        model:
          number_of_classes: 2
    pytorch_lightning_trainer_kwargs:
      accelerator: gpu
      enable_checkpointing: true
      enable_model_summary: false
      enable_progress_bar: false
      log_every_n_steps: 1
      min_epochs: 0
      max_epochs: 5
  pytorch_lightning_model:
    model_id: EfNet
    model_name: EfficientNet
    hyperparameters:
      device: cuda
      number_of_classes: 2
      optimiser:
        type: Adam
        kwargs:
          lr: 1.0e-05
      criterion:
        apply_weights: true
        device: cuda
        metadataframe:
          dataset_name: LIDC-IDRI
          data_preprocessing_protocol_number: 1
          lnva:
            names:
            - subtlety
            - internal_structure
            - calcification
            - sphericity
            - margin
            - lobulation
            - spiculation
            - texture
            score_counts:
              subtlety: 5
              internal_structure: 4
              calcification: 6
              sphericity: 5
              margin: 5
              lobulation: 5
              spiculation: 5
              texture: 5
            quantity: 8
          use_mode_for_internal_structure_and_calcification: false
      model:
        number_of_classes: 2
results_analysis:
  model_test_performance_metrics_dataframe:
    monitored_variables:
    - val_auroc
    - val_loss
    - last_epoch
  model_training_performance_metrics_figure:
    maximum_number_of_epochs: 5
seed_value: 1
